// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Introduction'
    },
    {
      type: 'doc',
      id: 'getting-started',
      label: 'Getting Started'
    },
    {
      type: 'category',
      label: 'Module 1: ROS 2 Fundamentals',
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-1-ros2'
        }
      ]
    },
    {
      type: 'category',
      label: 'Module 2: Simulation Environments',
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-2-gazebo-unity'
        }
      ]
    },
    {
      type: 'category',
      label: 'Module 3: AI Perception & Navigation',
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-3-nvidia-isaac'
        }
      ]
    },
    {
      type: 'category',
      label: 'Module 4: Humanoid Robotics Capstone',
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-4-vla-humanoid'
        }
      ]
    },
    {
      type: 'category',
      label: 'Additional Resources',
      items: [
        'assessment-framework',
        'progress-tracking',
        'accessibility-audit',
        'version-specific-documentation',
        'community-forum-setup',
        'quarterly-update-process',
        'offline-packaging',
        'weekly-plan',
        'chapter-template'
      ]
    }
  ],
};

module.exports = sidebars;